/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.ufmt.poo.bancoDeBancas.ui;

import br.ufmt.poo.BandoDeBancas.service.PessoaService;
import br.ufmt.poo.BandoDeBancas.service.impl.PessoaServiceImpl;
import javax.swing.JOptionPane;
import main.PessoaDTO;

/**
 *
 * @author aluno
 */
public class PessoaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PessoaJPanel
     */
    public PessoaJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        IDjLabel = new javax.swing.JLabel();
        NomejLabel = new javax.swing.JLabel();
        CPFjLabel = new javax.swing.JLabel();
        IDjTextField = new javax.swing.JTextField();
        NomejTextField = new javax.swing.JTextField();
        cpfjFormattedTextField = new javax.swing.JFormattedTextField();
        SalvarjButton = new javax.swing.JButton();
        CancelarjButton = new javax.swing.JButton();
        TabelajScrollPane = new javax.swing.JScrollPane();
        TabelaPessoajTable = new javax.swing.JTable();
        EditarjButton = new javax.swing.JButton();
        RemoverjButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        IDjLabel.setText("ID:");

        NomejLabel.setText("Nome:");

        CPFjLabel.setText("CPF:");

        IDjTextField.setEditable(false);

        try {
            cpfjFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        SalvarjButton.setText("Salvar");
        SalvarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarjButtonActionPerformed(evt);
            }
        });

        CancelarjButton.setText("Cancelar");
        CancelarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarjButtonActionPerformed(evt);
            }
        });

        TabelaPessoajTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelajScrollPane.setViewportView(TabelaPessoajTable);

        EditarjButton.setText("Editar");

        RemoverjButton.setText("Remover");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(IDjLabel))
                                .addComponent(CPFjLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(NomejLabel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RemoverjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EditarjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TabelajScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(SalvarjButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(CancelarjButton))
                                .addComponent(cpfjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(IDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addComponent(NomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDjLabel)
                    .addComponent(IDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomejLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfjFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CPFjLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalvarjButton)
                    .addComponent(CancelarjButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TabelajScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(EditarjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RemoverjButton)
                        .addContainerGap(213, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarjButtonActionPerformed
        IDjTextField.setText("");
        NomejTextField.setText("");
        cpfjFormattedTextField.setText(null);
    }//GEN-LAST:event_CancelarjButtonActionPerformed

    private void SalvarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarjButtonActionPerformed
        String id = IDjTextField.getText();
        String nome = NomejTextField.getText();
        String cpf = cpfjFormattedTextField.getText();
        
        PessoaDTO dto = new PessoaDTO(id, nome, cpf);
        
        //enviando para a service
        PessoaService service = new PessoaServiceImpl();
        try {
            service.salvar(dto);
            JOptionPane.showMessageDialog(this, "Salvo com sucesso!");
            CancelarjButtonActionPerformed(evt);
        } catch(Exception erro) {
            JOptionPane.showMessageDialog(this, erro.getMessage());
        }
        
        
        
        
        
    }//GEN-LAST:event_SalvarjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPFjLabel;
    private javax.swing.JButton CancelarjButton;
    private javax.swing.JButton EditarjButton;
    private javax.swing.JLabel IDjLabel;
    private javax.swing.JTextField IDjTextField;
    private javax.swing.JLabel NomejLabel;
    private javax.swing.JTextField NomejTextField;
    private javax.swing.JButton RemoverjButton;
    private javax.swing.JButton SalvarjButton;
    private javax.swing.JTable TabelaPessoajTable;
    private javax.swing.JScrollPane TabelajScrollPane;
    private javax.swing.JFormattedTextField cpfjFormattedTextField;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
